export const COMMON_PATHS = [
    '/usr/local/bin',
    '/opt/homebrew/opt/curl/bin',
    '~/.yarn/bin',
    '~/.config/yarn/global/node_modules/.bin',
    '~/.bun/bin',
    '~/.cargo/bin',
    '/opt/homebrew/opt/ruby/bin',
    '/opt/homebrew/bin',
    '/opt/homebrew/sbin',
    '/usr/local/opt/openssl/bin',
    '/usr/local/opt/ruby/bin',
    '/opt/miniconda3/bin',
    '/opt/homebrew/bin',
    '/usr/local/bin',
    '/usr/bin',
    '/bin',
    '/usr/sbin',
    '/sbin',
    '/usr/local/sbin',
    '/usr/local/opt/openssl/bin',
    '~/.go/bin',
    '~/.rvm/bin',
    '/opt/homebrew/opt/fzf/bin',
] as const;
